name: Update Home Games

on:
  schedule:
    - cron: '0 11 * * *'  # 7:00 AM Eastern Time
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Python script
        run: python generate_home_games.py  # <-- Adjust this path if needed

      - name: Commit and push updated HTML
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add index.html travel.html
          git commit -m "Auto-update home games for $(date +'%Y-%m-%d')"
          git push
