name: Update Home Games

on:
  schedule:
    - cron: '0 11 * * *'  # 7:00 AM Eastern Time
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Python script
        run: python generate_homegames.py

      - name: Commit changes locally
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add index.html travel.html
          git diff --cached --quiet || git commit -m "Auto-update home games for $(date +'%Y-%m-%d')"

      - name: Push using GitHub API
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GH_PAT }}
          script: |
            const { execSync } = require('child_process');
            execSync('git push origin HEAD:main', { stdio: 'inherit' });
